CREATE TABLE if not exists person
(
    id         bigint primary key generated by default as identity,
    last_name  varchar(255)             not null,
    first_name varchar(255)             not null,
    password   varchar                  not null,
    email      varchar(255)             not null,
    last_visit timestamp with time zone not null,
    username   varchar                  not null,
    update_date timestamp with time zone not null,
    create_date timestamp with time zone not null,
    role       varchar
);

alter table person add column image varchar(64);