CREATE TABLE USERS
(
    ID BIGINT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    PATRONYMIC VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PHONE VARCHAR(15) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
